### ISSUE TITLE
Run fail...

### ISSUE THREAD

**Issue by KevinNitroG** [longtoZ/auto-typer#1]
Help! :))

```
DevTools listening on ws://127.0.0.1:2546/devtools/browser/69f64da9-aba2-43a8-bb52-4698b4e54af4
Traceback (most recent call last):
  File "d:\Kevostro User Data\Downloads\Compressed\auto-typer-main\auto-typer-main\main.py", line 34, in <module>
    driver = webdriver.Chrome(service=service, options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\trann\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\trann\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\trann\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\trann\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\trann\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\trann\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 119.0.6045.124 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00C7A813+48355]
        (No symbol) [0x00C0C4B1]
        (No symbol) [0x00B15358]
        (No symbol) [0x00B361AC]
        (No symbol) [0x00B31EF3]
        (No symbol) [0x00B30579]
        (No symbol) [0x00B60C55]
        (No symbol) [0x00B6093C]
        (No symbol) [0x00B5A536]
        (No symbol) [0x00B382DC]
        (No symbol) [0x00B393DD]
        GetHandleVerifier [0x00EDAABD+2539405]
        GetHandleVerifier [0x00F1A78F+2800735]
        GetHandleVerifier [0x00F1456C+2775612]
        GetHandleVerifier [0x00D051E0+616112]
        (No symbol) [0x00C15F8C]
        (No symbol) [0x00C12328]
        (No symbol) [0x00C1240B]
        (No symbol) [0x00C04FF7]
        BaseThreadInitThunk [0x76647BA9+25]
        RtlInitializeExceptionChain [0x773BBD3B+107]
        RtlClearBits [0x773BBCBF+191]
```

![image](https://github.com/longtoZ/auto-typer/assets/86353526/52ad283c-34c7-4dbd-ba36-08efce59d810)

**Comment by KevinNitroG** [comment]
I figured out that it's the chromedriver version issue. Also another bug came out?

https://github.com/longtoZ/auto-typer/assets/86353526/affd6b36-1be1-4c6d-bb76-4b9bf4d612b4

Or idk how to use your script .-.

**Comment by longtoZ** [comment]
> I figured out that it's the chromedriver version issue. Also another bug came out?
> 
>  2023-11-13.10-10-57.mp4 
> Or idk how to use your script .-.

Hmmmmmmm idk why, too!
